# This is a basic workflow that is manually triggered

name: Build and Push pyclone docker container

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      tag_version: 
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Tag that will be given to the container when pushed to hub.ncsa.illinois.edu'
        # Default value if no value is explicitly provided
        default: '0.xx'
        # Input has to be provided for the workflow to run
        required: true

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Build pyclone Docker Image
      run: cd pyclone && sh build_pyclone.sh
    - name: Tag pyclone Docker Image
      run: cd pyclone && sh tag_latest_image.sh ${{ github.event.inputs.tag_version}}
    - name: Push tagged image to hub.ncsa.illinois.edu
      run: cd pyclone && sh publish_cyclone.sh ${{ github.event.inputs.tag_version}}
